
app_index:
    path: /
    controller: App\Controller\indexController::showIndexAction

app_live_show:
    path: /live
    controller: App\Controller\liveController::showLiveAction

#----------------------------------------------------------------------------------------FOOTBALLER:

app_details_fb:
    path: /footballer/{footballer}
    controller: App\Controller\detailsFootballerController::detailsFootballerAction

app_search_fb:
    path: /searchfb
    controller: App\Controller\searchFootballerController::searchFootballerAction

app_add_fb:
    path: /add/footballer/
    controller: App\Controller\addFootballerController::addFootballerAction

app_edit_details:
    path: /edit/footballer/{footballer}
    controller: App\Controller\EditDetailsFbController:editDetailsAction

#----------------------------------------------------------------------------------------TEAM:

app_search_team:
    path: /searchteam
    controller: App\Controller\searchTeamController::searchTeamAction

app_details_team:
    path: /detailsteam/{id}
    controller: App\Controller\detailsTeamController::detailsTeamAction

#----------------------------------------------------------------------------------------MATCHS:


app_show_match:
    path: /matchs
    controller: App\Controller\showMatchsController::showMatchAction

app_add_match:
    path: /add
    controller: App\Controller\addMatchController::createAction

app_details_match:
    path: /match/{id}
    controller: App\Controller\detailsMatchController::showDetailsAction

app_change_score:
    path: /match/addgoal/{id}
    controller: App\Controller\AddGoalMatchController::ChangeScoreAction

app_change_score_delete:
    path: /match/deletegoal/{id}
    controller: App\Controller\DeleteGoalMatchController::deleteGoalAction


#----------------------------------------------------------------------------------------STATS:

app_show_stats:
    path: /stats
    controller: App\Controller\StatsController:showStatsAction

#----------------------------------------------------------------------------------------REGISTRATION:

app_new_user:
    path: /registration
    controller: App\Controller\RegistrationController:addNewUserAction


#----------------------------------------------------------------------------------------TABLE:

app_show_table:
    path: /table
    controller: App\Controller\ShowTableController:showTableAction


