
app_index:
    path: /
    controller: App\Controller\indexController::showIndexAction

app_live_show:
    path: /live
    controller: App\Controller\liveController::showLiveAction

#----------------------------------------------------------------------------------------FOOTBALLER:

app_details_fb:
    path: /footballer/{footballer}
    controller: App\Controller\detailsFootballerController::detailsFootballerAction

app_search_fb:
    path: /searchfb
    controller: App\Controller\searchFootballerController::searchFootballerAction

app_add_fb:
    path: /add/footballer/
    controller: App\Controller\addFootballerController::addFootballerAction

app_edit_details:
    path: /edit/footballer/{footballer}
    controller: App\Controller\EditDetailsFbController:editDetailsAction

#----------------------------------------------------------------------------------------TEAM:

app_add_team:
    path: /addteam
    controller: App\Controller\AddTeamController:addTeamAction

app_edit_details_team:
    path: /editteam/{team}
    controller: App\Controller\EditDetailsTeamController:editDetailsAction

app_search_team:
    path: /searchteam
    controller: App\Controller\searchTeamController::searchTeamAction

app_details_team:
    path: /detailsteam/{team}
    controller: App\Controller\detailsTeamController::detailsTeamAction

#----------------------------------------------------------------------------------------MATCHS:


app_show_match:
    path: /matchs
    controller: App\Controller\showMatchsController::showMatchAction

app_add_match:
    path: /add
    controller: App\Controller\addMatchController::createAction

app_details_match:
    path: /match/{id}
    controller: App\Controller\detailsMatchController::showDetailsAction

app_change_score:
    path: /match/addgoal/{id}
    controller: App\Controller\AddGoalMatchController::ChangeScoreAction

app_change_score_delete:
    path: /match/deletegoal/{id}
    controller: App\Controller\DeleteGoalMatchController::deleteGoalAction

app_add_points:
    path: /match/addpoints/{id}
    controller: App\Controller\AddPointsController::addPointsAction

app_add_squad:
    path: /match/addsquad/{id}
    controller: App\Controller\AddSquadController:addSquadAction

app_delete_squad:
    path: /match/deletesquad/{id}
    controller: App\Controller\AddSquadController:deleteSquadAction

app_changFbH:
    path: /match/changefbhost/{id}
    controller: App\Controller\ChangeFootballerController:chagneFbHostAction

app_changFbG:
    path: /match/changefbguest/{id}
    controller: App\Controller\ChangeFootballerController:chagneFbGuestAction

#----------------------------------------------------------------------------------------STATS:

app_show_stats:
    path: /stats
    controller: App\Controller\StatsController:showStatsAction

#----------------------------------------------------------------------------------------REGISTRATION:

app_new_user:
    path: /registration
    controller: App\Controller\RegistrationController:addNewUserAction


#----------------------------------------------------------------------------------------TABLE:

app_show_table:
    path: /table
    controller: App\Controller\ShowTableController:showTableAction


#----------------------------------------------------------------------------------------LOGIN:

app_login:
    path: /login
    controller: App\Controller\SecurityController:login

logout:
    path: /logout
